server:
  port: 8080

spring:
  application.name: BankingManagementSystem
  config:
    import: classpath:config.yml
  datasource:
    url: jdbc:mysql://localhost:3306/banking_management?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

springdoc:
  cache:
    disabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration_time: ${JWT_TIME}

encryption:
  key: ${ENCRYPTION_KEY}

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}