server:
  port: 8080

spring:
  application.name: BankingManagementSystem
  config:
    import: classpath:config.yml
  datasource:
    url: jdbc:mysql://localhost:3306/banking_management?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: false
    change-log: classpath:/resources/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET}
  expiration_time: ${JWT_TIME}

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}
