DB_NAME:
DB_PASSWORD:

ADMIN_MAIL:
ADMIN_PASSWORD:
ADMIN_NAME:

JWT_SECRET: v3ryL0ngAndS3cureK3yF0rJWT512Algorithm@2025!MakeSureItHasAtLeast64Characters
JWT_TIME: 60m

ENCRYPTION_KEY: "your-strong-encryption-key-here-1234567890123456"